version: '3'

volumes:
  local_postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - db
    env_file:
      - ./envs/web
    volumes:
      - ./:/app/:z
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./envs/web
    ports:
      - "5432"

  requirements:
    image: python:3.9-buster
    profiles:
      - utils
    volumes:
      - ./:/app/:z

  tests-consultation_analyser:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
    image: tests_consultation_analyser
    env_file:
      - ./envs/tests
    profiles:
      - testing
    depends_on:
      - consultation_analyser-test-db

  consultation_analyser-test-db:
    image: postgres:13
    container_name: consultation_analyser_test_postgres
    env_file:
      - ./envs/tests
    expose:
      - "5432"